@echo off
cd c:\Users\Administrator\新建文件夹\888
echo Starting ETHUSDT Quantitative System...
echo.
echo Checking Python version...
python --version
echo.
echo Running diagnosis...
python diagnose.py
echo.
echo Starting Streamlit...
python -m streamlit run app_v3.py --server.headless=true --logger.level=info 2>&1 | tee streamlit.log
